lib/hotchpotch_web/router.ex
defmodule HotchpotchWeb.Router do
  use HotchpotchWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug HotchpotchWeb.Plugs.Auth, repo: Hotchpotch.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HotchpotchWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/users", UserController
    resources "/boards", BoardController

    resources "/sessions", SessionController, only: [:new, :create, :delete], singleton: true
  end

  # Other scopes may use custom stacks.
  # scope "/api", Hotchpotch do
  #   pipe_through :api
  # end
end

lib/hotchpotch_web/views/layout_view.ex
defmodule HotchpotchWeb.LayoutView do
  use HotchpotchWeb, :view

  import HotchpotchWeb.Helpers.TitleHelper
end

lib/hotchpotch_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="zh-Hans-CN">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= if @current_user do %>
      <%= tag :meta, name: "channel_token", content: Phoenix.Token.sign(@conn, "user", @current_user.id) %>
    <% end %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><%= page_title(assigns) %></title>
    <link rel="icon" href="<%= static_path(@conn, "/favicon.ico") %>" >
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link "嘿嘿黑板", class: "navbar-brand", to: page_path(@conn, :index) %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link "黑板", class: "nav-link", to: board_path(@conn, :index) %>
          </li>
        </ul>
        <ul class="navbar-nav">
          <%= if @current_user do %>
            <li id="nickname" class="nav-item"><%= link @current_user.nickname, class: "nav-link", to: user_path(@conn, :show, @current_user) %></li>
            <li class="nav-item"><%= link "退出", class: "nav-link", to: session_path(@conn, :delete), method: :delete %></li>
          <% else %>
            <li class="nav-item"><%= link "登录", class: "nav-link", to: session_path(@conn, :new) %></li>
            <li class="nav-item"><%= link "注册", class: "nav-link", to: user_path(@conn, :new) %></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main id="main" class="py-4" role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <%= render_existing @view_module, "scripts." <> @view_template, assigns %>
  </body>
</html>